
spring:
    datasource:
        url: jdbc:postgresql://localhost:8432/postgres
        username: age
        password: age

    jpa:
        #database-platform: org.hibernate.dialect.H2Dialect
        database: postgresql
        hibernate:

            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                format_sql: false
                use_sql_comments: false
    data:
        redis:
            host: 127.0.0.1
            port: 6379
    security:
        filter:
            dispatcher-types: request


jwt:
    secret: 8Zz5tw0Ionm3XPZZfN0NOml3z9FMfmpgXwovR9fp6ryDIoGRM8EPHAB6iHsc0fb

logging:
    level:
        com.bitnine.springsecurityjwtredis: warn
        org.hibernate.SQL: warn
        org.hibernate.type.descriptor.sql: warn





server:
    port: 10002